name: Branch standart validation

on:
  pull_request: # Escutando eventos relacionados a PRs
    types:
      - opened       # Quando a PR for aberta
      - synchronize  # Quando commits forem adicionados na PR (atualização)
      - reopened  
jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    container:
      image: alpine/git:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Make script executable
        run: chmod +x ./validate-branch.sh
      
      - name: Run script from file
        run: ./validate-branch.sh
